name: Install 2 on Windows

on:
  push:
    branches:
      - xxx

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy
          python -m pip install scipy
          python -m pip install cylp
